constructions = [
{"name": "Wooden cart", "id_in_game": 0, "chapter": 1.1, "skill": "Carts"},
{"name": "Wooden hut", "id_in_game": 1, "chapter": 1.1, "skill": "Huts"},
{"name": "Campfire", "id_in_game": 2, "chapter": 1.1, "skill": "Construction"},
{"name": "Stone cart", "id_in_game": 3, "chapter": 1.2, "skill": "Carts"},
{"name": "Stone hut", "id_in_game": 4, "chapter": 1.2, "skill": "Huts"},
{"name": "Bridge", "id_in_game": 5, "chapter": 1.3, "skill": "Progression"},
{"name": "Raft", "id_in_game": 6, "chapter": 1.3, "skill": "Progression"},
{"name": "Copper club", "id_in_game": 7, "chapter": 2.1, "skill": "Skill Item"},
{"name": "Stone oven", "id_in_game": 8, "chapter": 2.1, "skill": "Skill Item"},
{"name": "Boots", "id_in_game": 9, "chapter": 2.2, "skill": "Skill Item"},
{"name": "Raft sail", "id_in_game": 10, "chapter": 2.2, "skill": "Skill Item"},
{"name": "Tree house", "id_in_game": 11, "chapter": 2.2, "skill": "Progression"},
{"name": "Stone house", "id_in_game": 12, "chapter": 2.3, "skill": "Huts"},
{"name": "Cocowood raft", "id_in_game": 13, "chapter": 3.1, "skill": "Skill Item"},
{"name": "Cocowood hut", "id_in_game": 14, "chapter": 3.1, "skill": "Huts"},
{"name": "Iron stick", "id_in_game": 15, "chapter": 3.1, "skill": "Skill Item"},
{"name": "Cocowood soles", "id_in_game": 16, "chapter": 3.1, "skill": "Skill Item"},
{"name": "Reinforced belt", "id_in_game": 17, "chapter": 3.1, "skill": "Skill Item"},
{"name": "Cocowood cart", "id_in_game": 18, "chapter": 3.1, "skill": "Carts"},
{"name": "Gemstone ring", "id_in_game": 19, "chapter": 4.2, "skill": "Skill Item"},
{"name": "Small shrine", "id_in_game": 20, "chapter": 4.2, "skill": "Skill Item"},
{"name": "Gem pendant", "id_in_game": 21, "chapter": 4.2, "skill": "Skill Item"},
{"name": "Clay hut", "id_in_game": 22, "chapter": 4.2, "skill": "Huts"},
{"name": "Lobster pot", "id_in_game": 23, "chapter": 5.2, "skill": "Construction"},
{"name": "Boat", "id_in_game": 24, "chapter": 5.2, "skill": "Progression"},
{"name": "Cabin", "id_in_game": 25, "chapter": 5.2, "skill": "Huts"},
{"name": "Gathering gloves", "id_in_game": 26, "chapter": 5.4, "skill": "Skill Item"},
{"name": "Fishing rod", "id_in_game": 27, "chapter": 5.4, "skill": "Skill Item"},
{"name": "Wooden bow", "id_in_game": 28, "chapter": 5.4, "skill": "Skill Item"},
{"name": "Simple axe", "id_in_game": 29, "chapter": 5.4, "skill": "Skill Item"},
{"name": "Simple hammer", "id_in_game": 30, "chapter": 5.4, "skill": "Skill Item"},
{"name": "Copper shovel", "id_in_game": 31, "chapter": 5.4, "skill": "Skill Item"},
{"name": "Pan of soup", "id_in_game": 32, "chapter": 6, "skill": "Construction"},
{"name": "Liana rope", "id_in_game": 33, "chapter": 6, "skill": "Progression"},
{"name": "Fortify cart", "id_in_game": 34, "chapter": 7, "skill": "Carts"},
{"name": "Strengthen cart", "id_in_game": 35, "chapter": 7, "skill": "Carts"},
{"name": "Toughen cart", "id_in_game": 36, "chapter": 7, "skill": "Carts"},
{"name": "Fortify barricade", "id_in_game": 37, "chapter": 7, "skill": "Progression"},
{"name": "Limestone hut", "id_in_game": 38, "chapter": 8, "skill": "Huts"},
{"name": "Repair minecart", "id_in_game": 39, "chapter": 8, "skill": "Progression"},
{"name": "Magma hut", "id_in_game": 40, "chapter": 9, "skill": "Huts"},
{"name": "Magma shrine", "id_in_game": 41, "chapter": 9, "skill": "Skill Item"},
{"name": "Upgrade shrine", "id_in_game": 42, "chapter": 9, "skill": "Skill Item"},
{"name": "Ceremonial fire", "id_in_game": 43, "chapter": 10, "skill": "Progression"},
{"name": "Classic toolkit", "id_in_game": 44, "chapter": 10, "skill": "Skill Item"},
{"name": "Slingshot", "id_in_game": 45, "chapter": 10, "skill": "Progression"},
{"name": "Pearl necklace", "id_in_game": 46, "chapter": 10, "skill": "Skill Item"},
{"name": "Steel belt", "id_in_game": 47, "chapter": 10, "skill": "Skill Item"},
{"name": "Steel hut", "id_in_game": 48, "chapter": 10, "skill": "Skill Item"},
{"name": "Steel fork", "id_in_game": 49, "chapter": 10, "skill": "Skill Item"},
{"name": "Catapult", "id_in_game": 50, "chapter": 11, "skill": "Progression"},
{"name": "Load catapult", "id_in_game": 51, "chapter": 11, "skill": "Progression"},
{"name": "Titanstone hut", "id_in_game": 52, "chapter": 11, "skill": "Huts"},
]
constructions = {c["name"]: c for c in constructions}