jobs = [
    {"name": "Gather berries", "id_in_game": 0, "chapter": 1.1, "skill": "Farming"},
{"name": "Cut wood", "id_in_game": 1, "chapter": 1.1, "skill": "Woodcutting"},
{"name": "Catch fish", "id_in_game": 2, "chapter": 1.1, "skill": "Fishing"},
{"name": "Cook fish", "id_in_game": 3, "chapter": 1.1, "skill": "Cooking"},
{"name": "Dig stone", "id_in_game": 4, "chapter": 1.1, "skill": "Digging"},
{"name": "Pick apples", "id_in_game": 5, "chapter": 1.2, "skill": "Farming"},
{"name": "Hunt rabbit", "id_in_game": 6, "chapter": 1.3, "skill": "Hunting"},
{"name": "Cook rabbit", "id_in_game": 7, "chapter": 1.3, "skill": "Cooking"},
{"name": "Catch herring", "id_in_game": 8, "chapter": 2.1, "skill": "Fishing"},
{"name": "Gather grain", "id_in_game": 9, "chapter": 2.1, "skill": "Farming"},
{"name": "Bake bread", "id_in_game": 10, "chapter": 2.1, "skill": "Cooking"},
{"name": "Dig copper", "id_in_game": 11, "chapter": 2.1, "skill": "Digging"},
{"name": "Bake cake", "id_in_game": 12, "chapter": 2.1, "skill": "Cooking"},
{"name": "Hunt boar", "id_in_game": 13, "chapter": 2.2, "skill": "Hunting"},
{"name": "Cook boar", "id_in_game": 14, "chapter": 2.2, "skill": "Cooking"},
{"name": "Catch crab", "id_in_game": 15, "chapter": 3.1, "skill": "Fishing"},
{"name": "Cook crab", "id_in_game": 16, "chapter": 3.1, "skill": "Cooking"},
{"name": "Catch coconut", "id_in_game": 17, "chapter": 3.1, "skill": "Farming"},
{"name": "Cut cocowood", "id_in_game": 18, "chapter": 3.1, "skill": "Woodcutting"},
{"name": "Dig iron", "id_in_game": 19, "chapter": 3.1, "skill": "Digging"},
{"name": "Pick banana", "id_in_game": 20, "chapter": 3.1, "skill": "Farming"},
{"name": "Hunt goat", "id_in_game": 21, "chapter": 3.3, "skill": "Hunting"},
{"name": "Cook goat", "id_in_game": 22, "chapter": 3.3, "skill": "Cooking"},
{"name": "Hunt vulture", "id_in_game": 23, "chapter": 4.1, "skill": "Hunting"},
{"name": "Cook vulture", "id_in_game": 24, "chapter": 4.1, "skill": "Cooking"},
{"name": "Gather moss", "id_in_game": 25, "chapter": 4.2, "skill": "Farming"},
{"name": "Dig clay", "id_in_game": 26, "chapter": 4.2, "skill": "Digging"},
{"name": "Catch eel", "id_in_game": 27, "chapter": 4.2, "skill": "Fishing"},
{"name": "Cook eel", "id_in_game": 28, "chapter": 4.2, "skill": "Cooking"},
{"name": "Cut citrus wood", "id_in_game": 29, "chapter": 5.1, "skill": "Woodcutting"},
{"name": "Get dough", "id_in_game": 30, "chapter": 5.1, "skill": "Farming"},
{"name": "Bake biscuit", "id_in_game": 31, "chapter": 5.1, "skill": "Cooking"},
{"name": "Pick orange", "id_in_game": 32, "chapter": 5.1, "skill": "Farming"},
{"name": "Catch lobster", "id_in_game": 33, "chapter": 5.2, "skill": "Fishing"},
{"name": "Cook lobster", "id_in_game": 34, "chapter": 5.2, "skill": "Cooking"},
{"name": "Cook egg", "id_in_game": 35, "chapter": 5.4, "skill": "Cooking"},
{"name": "Bake pie", "id_in_game": 36, "chapter": 5.4, "skill": "Cooking"},
{"name": "Pick tomato", "id_in_game": 37, "chapter": 5.4, "skill": "Farming"},
{"name": "Catch shark", "id_in_game": 38, "chapter": 6, "skill": "Fishing"},
{"name": "Cook shark", "id_in_game": 39, "chapter": 6, "skill": "Cooking"},
{"name": "Hunt pelican", "id_in_game": 40, "chapter": 6, "skill": "Hunting"},
{"name": "Cook pelican", "id_in_game": 41, "chapter": 6, "skill": "Cooking"},
{"name": "Gather vegetable", "id_in_game": 42, "chapter": 6, "skill": "Farming"},
{"name": "Cook soup", "id_in_game": 43, "chapter": 6, "skill": "Cooking"},
{"name": "Gather liana", "id_in_game": 44, "chapter": 6, "skill": "Farming"},
{"name": "Get stew", "id_in_game": 45, "chapter": 7, "skill": "Digging"},
{"name": "Salvage ships", "id_in_game": 46, "chapter": 7, "skill": "Woodcutting"},
{"name": "Cook bull", "id_in_game": 47, "chapter": 7, "skill": "Cooking"},
{"name": "Hunt falcon", "id_in_game": 48, "chapter": 8, "skill": "Hunting"},
{"name": "Cook falcon", "id_in_game": 49, "chapter": 8, "skill": "Cooking"},
{"name": "Dig limestone", "id_in_game": 50, "chapter": 8, "skill": "Digging"},
{"name": "Catch seal", "id_in_game": 51, "chapter": 8, "skill": "Fishing"},
{"name": "Cook seal", "id_in_game": 52, "chapter": 8, "skill": "Cooking"},
{"name": "Gather corn", "id_in_game": 53, "chapter": 9, "skill": "Farming"},
{"name": "Dig magma", "id_in_game": 54, "chapter": 9, "skill": "Digging"},
{"name": "Catch koi", "id_in_game": 55, "chapter": 10, "skill": "Fishing"},
{"name": "Cook koi", "id_in_game": 56, "chapter": 10, "skill": "Cooking"},
{"name": "Gather mushroom", "id_in_game": 57, "chapter": 10, "skill": "Farming"},
{"name": "Shovel coal", "id_in_game": 58, "chapter": 10, "skill": "Digging"},
{"name": "Sell food", "id_in_game": 59, "chapter": 10, "skill": "Social"},
{"name": "Gather steel", "id_in_game": 60, "chapter": 10, "skill": "Digging"},
{"name": "Gather clam", "id_in_game": 61, "chapter": 11, "skill": "Fishing"},
{"name": "Cook clam", "id_in_game": 62, "chapter": 11, "skill": "Cooking"},
{"name": "Cut moldy wood", "id_in_game": 63, "chapter": 11, "skill": "Woodcutting"},
{"name": "Dig titan stone", "id_in_game": 64, "chapter": 11, "skill": "Digging"},
{"name": "Shoot beehive", "id_in_game": 65, "chapter": 11, "skill": "Hunting"},
{"name": "Pick portobello", "id_in_game": 66, "chapter": 11, "skill": "Farming"},
{"name": "Buy mixed salad", "id_in_game": 67, "chapter": 10, "skill": "Social"},
{"name": "Buy packed meal", "id_in_game": 68, "chapter": 10, "skill": "Social"},
]
jobs = {job["name"]: job for job in jobs}