location_logic = {
    "Explore the area": ["","","","","","","","","","","","","","",""],
    "Explore the cave": ["","","","","","","","","","","","","","",""],
    "Fight cave spider": ["","","","","","","","","","","","","","",""],
    "Explore cave exit": ["","","","","","","","","","","","","","",""],
    "Cross the lake": ["Bridge","Cut wood","Dig stone","","","","","","","","","","","",""],
    "Fight wolf": ["Bridge","Cut wood","Dig stone","","","","","","","","","","","",""],
    "Explore the shore": ["Bridge","Cut wood","Dig stone","","","","","","","","","","","",""],
    "Board your raft": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Sail to the island": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk to village": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Meet fisher": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Meet farmer": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Meet miner": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Meet baker": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Meet the mayor": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter forest": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Campfire party!": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Explore forest": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight wolf pack": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Search forest": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Use lookout": ["Bridge","Cut wood","Dig stone","Raft","Tree house","","","","","","","","","",""],
    "Convince bandits": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Convince bandits (2)": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Return to town": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Talk to mayor": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Board your raft (2)": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Sail to ship": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Board ship": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight deckhand": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight cannoneer": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight captain": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight octopus": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Explore sea cave": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Explore beach": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter mineshaft": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Board river": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight rats": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Paddle upstream": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Proceed in mine": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Paddle forth": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight bats": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Pass waterfall": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Pass narrow path": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Explore cave": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight bear": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Flee from bear": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Exit cave": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Climb mountain": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk around": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Jump over ravine": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Climb to temple": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Tiger teaching": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Parrot teaching": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Goat teaching": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Bear teaching": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Continue climb": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Climb to top": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight lizard": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight baby dragon": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight dragon": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Climb down": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter desert": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk to oasis": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight vultures": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk to pyramid": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter pyramid": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Emerald temple": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Pass spike trap": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Carve out gem": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight chameleon": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Emerald exit": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Ruby temple": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight scarabs": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Dig up gem": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Catch boulder": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Ruby exit": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Sapphire temple": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Paddle in temple": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight piranhas": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Pull in gemstone": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight crocodile": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Sapphire exit": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter crypt": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight scorpion": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "See sarcophagus": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Exit pyramid": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Meet nomads": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Catch a ride": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk to gate": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Persuade guard": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter city": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Talk to nomads": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter market": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fruit vendor": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Catch thieves": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Pastries vendor": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk to docks": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Cage fishers": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Boat builders": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter lowtown": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Fight robbers": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Proceed in alley": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Coax bouncer": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter tavern": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Dance battle": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Play cards": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Mysterious type": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Dragon's equals": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Leave tavern": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Move along": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Enter orphanage": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Walk to eatery": ["Bridge","Cut wood","Dig stone","Raft","","","","","","","","","","",""],
    "Return to the kids": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Go to hightown": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Tools vendor": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Pie vendor": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Tomato vendor": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Enter the games": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Scavenger hunt": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Raft racing": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Bullseye shot": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Claim medal": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Enter palace": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Friendly chat": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Meet elder": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Fight guards": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Flee to docks": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","","","","","","","","","",""],
    "Board boat": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Set sail": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Sail to smoke": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Sail west": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Sail north": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Sail east": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Sail to volcano": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Fight sharks": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Dock at beach": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Follow locals": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Meet chieftain": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Meet hunters": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Meet gatherers": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Weed out nettles": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Enter jungle": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Follow stream": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Cross swamp": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Climb rocks": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Bushwhack along": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Fight jaguar": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Mud cover": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Sneak past": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Abandoned camp": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Leave campsite": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Jump gorge": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Swing across": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Gather liana","Liana rope","","","","","",""],
    "Follow the sounds": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Meet monkeys": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Get ransacked": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Fight gorilla": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Exit jungle": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Walk to temple": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Climb stairs": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Inspect hourglass": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Funnel hourglass": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Climb down (2)": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Follow stream (2)": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Board boat (2)": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Dock at harbor": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Follow guards": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Talk to officer": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Enter cell": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Meet cellmate": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Help digging": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Go to dining area": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Meet others": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Pick a fight": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Return to cell": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Work on tunnel": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Go to yard": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","","","","","","","",""],
    "Return to diner": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Talk to guard": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter the arena": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight gladiator": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Claim shield": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Reject shield": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight champion": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Short break": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Return to arena": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight bull": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Hunt bull": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight lion": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Final break": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Funnel shield": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Return for finale": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight hydra": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight chimera": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Leave the arena": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Get escorted out": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Board boat (3)": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Dock aside ships": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet fleet people": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Walk to quarry": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter quarry": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Descend layer": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter old mine": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Climb rails": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Ride minecart": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Dig limestone","Repair minecart","","","",""],
    "Inspect door": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter treasury": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Explore treasury": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Inspect statues": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Read inscriptions": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight golem": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Climb to throne": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Bronze dragon": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Exit treasury": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Dig through snow": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Walk frozen lake": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Sail through ice": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Explore mudbank": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight walrus": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet poachers": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Inquire more": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Follow poachers": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Look at dragon": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Inspect area": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fight poachers": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Sabotage camp": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Approach dragon": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Cut ropes": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Funnel tooth": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Dragon ride": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Board boat (4)": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Approach shore": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Dock on shore": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Walk inland": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter village": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Inspect bakery": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Inspect farm": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Inspect shrine": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet stranger": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Exit village": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Path around lava": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Cut down tree": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Cross lava flow": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Climb volcano": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Jump in": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet her": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Amy's story": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Like her?": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Wait, us?": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Your part in this": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Different how?": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "So what now?": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Exit on dragon": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Fly away": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Cross clouds": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Land on cliff": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet cliff people": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Continue cliff chat": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter mountain": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Climb to low layer": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter forage shack": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet forager": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Mushroom school": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Exit shack": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Walk to waterfall": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet cleaner": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Catch soles": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Catch cart": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Catch statue": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Climb back up": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Enter main square": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Introduce yourself": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Ignite the fire": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Enter the crowd": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Exit the square": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Walk to top layer": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Meet blacksmith": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Approach dog": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Take dog's toy": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Follow dog": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Pillage nest": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Shoo crows": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Empty nest": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Exit top layer": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","","","","","",""],
    "Approach vault": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Meet keepers": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "The Architect?": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Inspect vault": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Open vault door": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Talk to keepers": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Enter the vault": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Approach statue": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Attack titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Dodge titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Backshot titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Trip titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Block titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Counter titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Approach debris": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Fire at titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","Cut moldy wood","Dig titan stone","Catapult","Load catapult"],
    "Fire at ceiling": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","Cut moldy wood","Dig titan stone","Catapult","Load catapult"],
    "Return to titan": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Read inscription": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Inspect core": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Funnel titan core": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Disable titan core": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
    "Exit the vault": ["Bridge","Cut wood","Dig stone","Raft","Cook egg","Cut citrus wood","Boat","Salvage ships","Fortify barricade","Shovel coal","Ceremonial fire","","","",""],
}