jobs = [
    {"name": "Gather berries", "chapter": 1, "skill": "Farming"},
    {"name": "Cut wood", "chapter": 1, "skill": "Woodcutting"},
    {"name": "Catch fish", "chapter": 1, "skill": "Fishing"},
    {"name": "Cook fish", "chapter": 1, "skill": "Cooking"},
    {"name": "Dig stone", "chapter": 1, "skill": "Digging"},
    {"name": "Pick apples", "chapter": 1, "skill": "Farming"},
    {"name": "Hunt rabbit", "chapter": 1, "skill": "Hunting"},
    {"name": "Cook rabbit", "chapter": 1, "skill": "Cooking"},
    {"name": "Catch herring", "chapter": 2, "skill": "Fishing"},
    {"name": "Gather grain", "chapter": 2, "skill": "Farming"},
    {"name": "Bake bread", "chapter": 2, "skill": "Cooking"},
    {"name": "Dig copper", "chapter": 2, "skill": "Digging"},
    {"name": "Bake cake", "chapter": 2, "skill": "Cooking"},
    {"name": "Hunt boar", "chapter": 2, "skill": "Hunting"},
    {"name": "Cook boar", "chapter": 2, "skill": "Cooking"},
    {"name": "Catch crab", "chapter": 3, "skill": "Fishing"},
    {"name": "Cook crab", "chapter": 3, "skill": "Cooking"},
    {"name": "Catch coconut", "chapter": 3, "skill": "Farming"},
    {"name": "Cut cocowood", "chapter": 3, "skill": "Woodcutting"},
    {"name": "Dig iron", "chapter": 3, "skill": "Digging"},
    {"name": "Pick banana", "chapter": 3, "skill": "Farming"},
    {"name": "Hunt goat", "chapter": 3, "skill": "Hunting"},
    {"name": "Cook goat", "chapter": 3, "skill": "Cooking"},
    {"name": "Hunt vulture", "chapter": 4, "skill": "Hunting"},
    {"name": "Cook vulture", "chapter": 4, "skill": "Cooking"},
    {"name": "Gather moss", "chapter": 4, "skill": "Farming"},
    {"name": "Dig clay", "chapter": 4, "skill": "Digging"},
    {"name": "Catch eel", "chapter": 4, "skill": "Fishing"},
    {"name": "Cook eel", "chapter": 4, "skill": "Cooking"},
    {"name": "Cut citrus wood", "chapter": 5, "skill": "Woodcutting"},
    {"name": "Get dough", "chapter": 5, "skill": "Farming"},
    {"name": "Bake biscuit", "chapter": 5, "skill": "Cooking"},
    {"name": "Pick orange", "chapter": 5, "skill": "Farming"},
    {"name": "Catch lobster", "chapter": 5, "skill": "Fishing"},
    {"name": "Cook lobster", "chapter": 5, "skill": "Cooking"},
    {"name": "Cook egg", "chapter": 5, "skill": "Cooking"},
    {"name": "Bake pie", "chapter": 5, "skill": "Cooking"},
    {"name": "Pick tomato", "chapter": 5, "skill": "Farming"},
    {"name": "Catch shark", "chapter": 6, "skill": "Fishing"},
    {"name": "Cook shark", "chapter": 6, "skill": "Cooking"},
    {"name": "Hunt pelican", "chapter": 6, "skill": "Hunting"},
    {"name": "Cook pelican", "chapter": 6, "skill": "Cooking"},
    {"name": "Gather vegetable", "chapter": 6, "skill": "Farming"},
    {"name": "Cook soup", "chapter": 6, "skill": "Cooking"},
    {"name": "Gather liana", "chapter": 6, "skill": "Farming"},
    {"name": "Get stew", "chapter": 7, "skill": "Digging"},
    {"name": "Salvage ships", "chapter": 7, "skill": "Woodcutting"},
    {"name": "Cook bull", "chapter": 7, "skill": "Cooking"},
    {"name": "Hunt falcon", "chapter": 8, "skill": "Hunting"},
    {"name": "Cook falcon", "chapter": 8, "skill": "Cooking"},
    {"name": "Dig limestone", "chapter": 8, "skill": "Digging"},
    {"name": "Catch seal", "chapter": 8, "skill": "Fishing"},
    {"name": "Cook seal", "chapter": 8, "skill": "Cooking"},
    {"name": "Gather corn", "chapter": 9, "skill": "Farming"},
    {"name": "Dig magma", "chapter": 9, "skill": "Digging"},
    {"name": "Catch koi", "chapter": 10, "skill": "Fishing"},
    {"name": "Cook koi", "chapter": 10, "skill": "Cooking"},
    {"name": "Gather mushroom", "chapter": 10, "skill": "Farming"},
    {"name": "Shovel coal", "chapter": 10, "skill": "Digging"},
    {"name": "Sell food", "chapter": 10, "skill": "Social"},
    {"name": "Gather steel", "chapter": 10, "skill": "Digging"},
    {"name": "Gather clam", "chapter": 11, "skill": "Fishing"},
    {"name": "Cook clam", "chapter": 11, "skill": "Cooking"},
    {"name": "Cut moldy wood", "chapter": 11, "skill": "Woodcutting"},
    {"name": "Dig titan stone", "chapter": 11, "skill": "Digging"},
    {"name": "Shoot beehive", "chapter": 11, "skill": "Hunting"},
    {"name": "Pick portobello", "chapter": 11, "skill": "Farming"},
    {"name": "Buy mixed salad", "chapter": 10, "skill": "Social"},
    {"name": "Buy packed meal", "chapter": 10, "skill": "Social"},
]

constructions = [
    {"name": "Wooden cart", "chapter": 1, "skill": "Construction"},
    {"name": "Wooden hut", "chapter": 1, "skill": "Construction"},
    {"name": "Campfire", "chapter": 1, "skill": "Construction"},
    {"name": "Stone cart", "chapter": 1, "skill": "Construction"},
    {"name": "Stone hut", "chapter": 1, "skill": "Construction"},
    {"name": "Bridge", "chapter": 1, "skill": "Construction"},
    {"name": "Raft", "chapter": 1, "skill": "Construction"},
    {"name": "Copper club", "chapter": 2, "skill": "Construction"},
    {"name": "Stone oven", "chapter": 2, "skill": "Construction"},
    {"name": "Boots", "chapter": 2, "skill": "Construction"},
    {"name": "Raft sail", "chapter": 2, "skill": "Construction"},
    {"name": "Tree house", "chapter": 2, "skill": "Construction"},
    {"name": "Stone house", "chapter": 2, "skill": "Construction"},
    {"name": "Cocowood raft", "chapter": 3, "skill": "Construction"},
    {"name": "Cocowood hut", "chapter": 3, "skill": "Construction"},
    {"name": "Iron stick", "chapter": 3, "skill": "Construction"},
    {"name": "Cocowood soles", "chapter": 3, "skill": "Construction"},
    {"name": "Reinforced belt", "chapter": 3, "skill": "Construction"},
    {"name": "Cocowood cart", "chapter": 3, "skill": "Construction"},
    {"name": "Gemstone ring", "chapter": 4, "skill": "Construction"},
    {"name": "Small shrine", "chapter": 4, "skill": "Construction"},
    {"name": "Gem pendant", "chapter": 4, "skill": "Construction"},
    {"name": "Clay hut", "chapter": 4, "skill": "Construction"},
    {"name": "Lobster pot", "chapter": 5, "skill": "Construction"},
    {"name": "Boat", "chapter": 5, "skill": "Construction"},
    {"name": "Cabin", "chapter": 5, "skill": "Construction"},
    {"name": "Gathering gloves", "chapter": 5, "skill": "Social"},
    {"name": "Fishing rod", "chapter": 5, "skill": "Social"},
    {"name": "Wooden bow", "chapter": 5, "skill": "Social"},
    {"name": "Simple axe", "chapter": 5, "skill": "Social"},
    {"name": "Simple hammer", "chapter": 5, "skill": "Social"},
    {"name": "Copper shovel", "chapter": 5, "skill": "Social"},
    {"name": "Pan of soup", "chapter": 6, "skill": "Construction"},
    {"name": "Liana rope", "chapter": 6, "skill": "Construction"},
    {"name": "Fortify cart", "chapter": 7, "skill": "Construction"},
    {"name": "Strengthen cart", "chapter": 7, "skill": "Construction"},
    {"name": "Toughen cart", "chapter": 7, "skill": "Construction"},
    {"name": "Fortify barricade", "chapter": 7, "skill": "Construction"},
    {"name": "Limestone hut", "chapter": 8, "skill": "Construction"},
    {"name": "Repair minecart", "chapter": 8, "skill": "Construction"},
    {"name": "Magma hut", "chapter": 9, "skill": "Construction"},
    {"name": "Magma shrine", "chapter": 9, "skill": "Construction"},
    {"name": "Upgrade shrine", "chapter": 9, "skill": "Construction"},
    {"name": "Ceremonial fire", "chapter": 10, "skill": "Digging"},
    {"name": "Classic toolkit", "chapter": 10, "skill": "Social"},
    {"name": "Slingshot", "chapter": 10, "skill": "Social"},
    {"name": "Pearl necklace", "chapter": 10, "skill": "Social"},
    {"name": "Steel belt", "chapter": 10, "skill": "Construction"},
    {"name": "Steel hut", "chapter": 10, "skill": "Construction"},
    {"name": "Steel fork", "chapter": 10, "skill": "Construction"},
    {"name": "Catapult", "chapter": 11, "skill": "Construction"},
    {"name": "Load catapult", "chapter": 11, "skill": "Construction"},
    {"name": "Titanstone hut", "chapter": 11, "skill": "Construction"},
]